set number
set mouse=a
set numberwidth=1
set clipboard=unnamed
syntax enable
set showcmd
set ruler
set cursorline
set encoding=utf-8
set fileencoding=uft-8
set showmatch
set sw=2
set relativenumber
set laststatus=2
set noshowmode

source ~/config/.vim/plugins.vim
source ~/config/.vim/plugins-config.vim
source ~/config/.vim/maps.vim
